# Generated by Django 5.2.12 on 2026-03-23 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Трек',
                'verbose_name_plural': 'Треки',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Kart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('avg_lap_ms', models.IntegerField(default=0)),
                ('best_lap_ms', models.IntegerField(default=0)),
                ('total_races', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='karts', to='timing.track')),
            ],
            options={
                'verbose_name': 'Карт',
                'verbose_name_plural': 'Карты',
                'ordering': ['track', 'number'],
                'unique_together': {('track', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Heat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('scheduled_at', models.DateTimeField()),
                ('laps_count', models.PositiveSmallIntegerField(default=0)),
                ('session_type', models.CharField(blank=True, max_length=50)),
                ('championship', models.CharField(blank=True, max_length=50)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heats', to='timing.track')),
            ],
            options={
                'verbose_name': 'Заезд',
                'verbose_name_plural': 'Заезды',
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('team', models.CharField(blank=True, max_length=100)),
                ('avg_lap_ms', models.IntegerField(default=0)),
                ('best_lap_ms', models.IntegerField(default=0)),
                ('total_races', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='timing.track')),
            ],
            options={
                'verbose_name': 'Гонщик',
                'verbose_name_plural': 'Гонщики',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HeatParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('laps_completed', models.PositiveSmallIntegerField(default=0)),
                ('best_lap_ms', models.IntegerField(default=0)),
                ('avg_lap_ms', models.IntegerField(default=0)),
                ('dev_lap_ms', models.IntegerField(default=0)),
                ('s1_laps', models.PositiveSmallIntegerField(default=0)),
                ('s1_best_ms', models.IntegerField(default=0)),
                ('s2_laps', models.PositiveSmallIntegerField(default=0)),
                ('s2_best_ms', models.IntegerField(default=0)),
                ('s3_laps', models.PositiveSmallIntegerField(default=0)),
                ('s3_best_ms', models.IntegerField(default=0)),
                ('gap_to_leader_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='timing.driver')),
                ('heat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='timing.heat')),
                ('kart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='timing.kart')),
            ],
            options={
                'verbose_name': 'Участие в заезде',
                'verbose_name_plural': 'Участия в заездах',
                'ordering': ['heat', 'position'],
                'unique_together': {('heat', 'driver')},
            },
        ),
    ]
