# Generated by Django 5.0.6 on 2026-02-19 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='heatparticipation',
            options={},
        ),
        migrations.RemoveField(
            model_name='heatparticipation',
            name='total_time_ms',
        ),
        migrations.RemoveField(
            model_name='kart',
            name='last_seen',
        ),
        migrations.AddField(
            model_name='driver',
            name='avg_lap_ms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='driver',
            name='best_lap_ms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='driver',
            name='total_races',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='heat',
            name='championship',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='heat',
            name='session_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='heatparticipation',
            name='avg_lap_ms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='heatparticipation',
            name='dev_lap_ms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='heatparticipation',
            name='gap_to_leader_ms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='heatparticipation',
            name='s1_best_ms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='heatparticipation',
            name='s1_laps',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='heatparticipation',
            name='s2_best_ms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='heatparticipation',
            name='s2_laps',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='heatparticipation',
            name='s3_best_ms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='heatparticipation',
            name='s3_laps',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kart',
            name='avg_lap_ms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kart',
            name='best_lap_ms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kart',
            name='total_races',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='driver',
            name='external_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='driver',
            name='team',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='driver',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.track'),
        ),
        migrations.AlterField(
            model_name='heat',
            name='external_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='heat',
            name='laps_count',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='heat',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='heat',
            name='scheduled_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='heat',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.track'),
        ),
        migrations.AlterField(
            model_name='heatparticipation',
            name='best_lap_ms',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='heatparticipation',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.driver'),
        ),
        migrations.AlterField(
            model_name='heatparticipation',
            name='heat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.heat'),
        ),
        migrations.AlterField(
            model_name='heatparticipation',
            name='kart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.kart'),
        ),
        migrations.AlterField(
            model_name='heatparticipation',
            name='laps_completed',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='heatparticipation',
            name='position',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='kart',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='kart',
            name='number',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='kart',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.track'),
        ),
    ]
