# Generated by Django 5.0.6 on 2026-02-12 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Трек',
                'verbose_name_plural': 'Треки',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Kart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Номер')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='karts', to='core.track', verbose_name='Трек')),
            ],
            options={
                'verbose_name': 'Карт',
                'verbose_name_plural': 'Карты',
                'ordering': ['track', 'number'],
                'unique_together': {('track', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Heat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(unique=True, verbose_name='Внешний ID')),
                ('scheduled_at', models.DateTimeField(verbose_name='Дата и время')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Название')),
                ('laps_count', models.PositiveSmallIntegerField(default=0, verbose_name='Количество кругов')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heats', to='core.track', verbose_name='Трек')),
            ],
            options={
                'verbose_name': 'Заезд',
                'verbose_name_plural': 'Заезды',
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(unique=True, verbose_name='Внешний ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('team', models.CharField(blank=True, max_length=100, verbose_name='Команда')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='core.track', verbose_name='Трек')),
            ],
            options={
                'verbose_name': 'Гонщик',
                'verbose_name_plural': 'Гонщики',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HeatParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(verbose_name='Позиция')),
                ('best_lap_ms', models.IntegerField(verbose_name='Лучший круг (мс)')),
                ('total_time_ms', models.IntegerField(blank=True, null=True, verbose_name='Общее время (мс)')),
                ('laps_completed', models.PositiveSmallIntegerField(default=0, verbose_name='Пройдено кругов')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.driver', verbose_name='Гонщик')),
                ('heat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.heat', verbose_name='Заезд')),
                ('kart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.kart', verbose_name='Карт')),
            ],
            options={
                'verbose_name': 'Участие в заезде',
                'verbose_name_plural': 'Участия в заездах',
                'ordering': ['heat', 'position'],
                'unique_together': {('heat', 'driver')},
            },
        ),
    ]
